### PR TITLE
Cleaning up the blog posts for this issue

### PR DESCRIPTION
**Pull request by kushaldas**

### CODE REVIEW

**Comment by ghost** [comment]
I perfectly agree with most of the changes, but I'm not sure with those two:
- championshuttler (Shivam Singhal ) - MozAMU: Mozilla Addons Development at AMU
- Shashank Kumar - MozAMU - My first talk for Mozilla and first visit to Aligarh Muslim University - 24th February 2018

Is there a specific reason to exclude these posts?

**Comment by kushaldas** [comment]
I personally thought of only few selected blog posts which are good (at least in my eyes) for the newsletter, not all the posts people write. But, I will let this on all of you editors.

**Comment by ghost** [comment]
This is indeed a difficult question that has been discussed already. I fear that it could be a motivation killer if someone feels ignored, but on the other hand it will be impossible to curate all posts in a timely manner, especially if this year's summer training has started.
So we should define some rules that should be as objective and fair as possible. I could think of 
- only one blog post per author and issue
- putting posts in categories (e.g. how-to, news, revision, report) and appropriately weight them
- exclude short status updates

I think this could be doable and appropriate, or am I overseeing something? Does anyone have other suggestions?

**Comment by kushaldas** [comment]
> I fear that it could be a motivation killer if someone feels ignored, but on the other hand it will be impossible to curate all posts in a timely manner, especially if this year's summer training has started.

We never tell that we will write about everyone or every blog post in the newsletter, or anywhere else, the same goes to the people whom we verify after summer training when the companies ask us during the interview process. It is under the mentors to choose who all we can verify as ready to be hired.

Also, in the same reason, my initial idea was to put all the blogs which may look nice in first read, and then select a few which makes sense.

**Comment by ghost** [comment]
I've included most changes as suggested, a first complete draft can now be found [here](https://github.com/dgplug/newsletter/blob/master/issues/2018-03-19/issue_2018-03-19.md).

**Pull request closed without merging**
